namespace DevExpressReportMVCDemo.Reports
{
    partial class AllTables
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery1 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column1 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression1 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table1 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column2 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression2 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column3 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression3 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column4 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression4 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column5 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression5 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column6 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression6 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery2 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column7 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression7 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table2 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column8 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression8 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column9 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression9 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column10 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression10 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column11 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression11 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column12 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression12 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery3 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column13 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression13 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table3 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column14 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression14 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column15 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression15 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column16 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression16 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery4 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column17 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression17 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table4 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column18 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression18 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column19 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression19 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column20 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression20 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column21 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression21 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column22 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression22 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column23 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression23 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column24 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression24 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column25 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression25 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column26 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression26 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column27 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression27 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery5 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column28 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression28 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table5 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column29 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression29 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery6 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column30 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression30 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table6 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column31 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression31 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column32 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression32 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column33 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression33 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column34 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression34 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column35 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression35 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column36 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression36 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column37 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression37 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column38 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression38 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column39 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression39 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column40 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression40 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column41 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression41 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column42 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression42 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column43 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression43 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column44 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression44 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column45 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression45 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column46 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression46 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column47 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression47 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery7 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column48 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression48 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table7 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column49 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression49 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column50 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression50 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column51 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression51 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column52 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression52 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column53 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression53 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column54 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression54 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column55 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression55 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column56 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression56 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column57 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression57 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column58 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression58 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column59 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression59 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column60 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression60 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column61 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression61 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column62 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression62 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column63 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression63 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column64 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression64 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column65 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression65 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column66 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression66 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column67 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression67 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column68 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression68 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column69 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression69 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column70 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression70 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column71 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression71 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column72 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression72 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column73 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression73 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery8 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column74 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression74 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table8 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column75 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression75 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column76 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression76 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column77 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression77 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column78 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression78 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column79 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression79 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery9 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column80 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression80 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table9 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column81 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression81 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column82 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression82 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column83 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression83 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column84 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression84 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column85 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression85 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column86 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression86 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery10 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column87 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression87 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table10 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column88 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression88 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column89 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression89 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column90 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression90 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column91 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression91 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column92 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression92 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column93 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression93 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column94 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression94 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column95 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression95 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column96 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression96 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column97 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression97 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column98 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression98 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column99 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression99 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column100 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression100 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery11 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column101 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression101 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table11 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column102 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression102 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column103 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression103 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column104 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression104 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery12 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column105 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression105 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table12 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column106 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression106 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column107 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression107 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column108 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression108 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column109 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression109 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column110 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression110 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column111 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression111 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column112 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression112 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column113 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression113 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column114 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression114 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column115 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression115 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery13 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column116 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression116 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table13 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column117 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression117 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column118 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression118 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery14 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column119 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression119 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table14 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column120 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression120 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column121 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression121 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column122 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression122 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column123 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression123 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column124 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression124 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column125 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression125 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column126 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression126 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column127 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression127 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column128 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression128 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column129 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression129 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column130 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression130 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery15 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column131 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression131 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table15 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column132 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression132 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column133 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression133 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery16 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column134 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression134 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table16 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column135 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression135 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column136 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression136 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column137 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression137 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column138 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression138 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column139 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression139 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column140 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression140 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column141 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression141 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column142 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression142 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column143 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression143 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column144 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression144 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column145 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression145 = new DevExpress.DataAccess.Sql.ColumnExpression();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AllTables));
            this.TopMargin = new DevExpress.XtraReports.UI.TopMarginBand();
            this.BottomMargin = new DevExpress.XtraReports.UI.BottomMarginBand();
            this.Detail = new DevExpress.XtraReports.UI.DetailBand();
            this.sqlDataSource1 = new DevExpress.DataAccess.Sql.SqlDataSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // TopMargin
            // 
            this.TopMargin.Name = "TopMargin";
            // 
            // BottomMargin
            // 
            this.BottomMargin.Name = "BottomMargin";
            // 
            // Detail
            // 
            this.Detail.Name = "Detail";
            // 
            // sqlDataSource1
            // 
            this.sqlDataSource1.ConnectionName = "nwind";
            this.sqlDataSource1.Name = "sqlDataSource1";
            columnExpression1.ColumnName = "CategoryID";
            table1.Name = "Categories";
            columnExpression1.Table = table1;
            column1.Expression = columnExpression1;
            columnExpression2.ColumnName = "CategoryName";
            columnExpression2.Table = table1;
            column2.Expression = columnExpression2;
            columnExpression3.ColumnName = "Description";
            columnExpression3.Table = table1;
            column3.Expression = columnExpression3;
            columnExpression4.ColumnName = "Picture";
            columnExpression4.Table = table1;
            column4.Expression = columnExpression4;
            columnExpression5.ColumnName = "Icon_17";
            columnExpression5.Table = table1;
            column5.Expression = columnExpression5;
            columnExpression6.ColumnName = "Icon_25";
            columnExpression6.Table = table1;
            column6.Expression = columnExpression6;
            selectQuery1.Columns.Add(column1);
            selectQuery1.Columns.Add(column2);
            selectQuery1.Columns.Add(column3);
            selectQuery1.Columns.Add(column4);
            selectQuery1.Columns.Add(column5);
            selectQuery1.Columns.Add(column6);
            selectQuery1.Name = "Categories";
            selectQuery1.Tables.Add(table1);
            columnExpression7.ColumnName = "ProductID";
            table2.Name = "CategoryProducts";
            columnExpression7.Table = table2;
            column7.Expression = columnExpression7;
            columnExpression8.ColumnName = "SupplierID";
            columnExpression8.Table = table2;
            column8.Expression = columnExpression8;
            columnExpression9.ColumnName = "ProductName";
            columnExpression9.Table = table2;
            column9.Expression = columnExpression9;
            columnExpression10.ColumnName = "CategoryName";
            columnExpression10.Table = table2;
            column10.Expression = columnExpression10;
            columnExpression11.ColumnName = "Picture";
            columnExpression11.Table = table2;
            column11.Expression = columnExpression11;
            columnExpression12.ColumnName = "Description";
            columnExpression12.Table = table2;
            column12.Expression = columnExpression12;
            selectQuery2.Columns.Add(column7);
            selectQuery2.Columns.Add(column8);
            selectQuery2.Columns.Add(column9);
            selectQuery2.Columns.Add(column10);
            selectQuery2.Columns.Add(column11);
            selectQuery2.Columns.Add(column12);
            selectQuery2.Name = "CategoryProducts";
            selectQuery2.Tables.Add(table2);
            columnExpression13.ColumnName = "ProductName";
            table3.Name = "CustomerReports";
            columnExpression13.Table = table3;
            column13.Expression = columnExpression13;
            columnExpression14.ColumnName = "CompanyName";
            columnExpression14.Table = table3;
            column14.Expression = columnExpression14;
            columnExpression15.ColumnName = "OrderDate";
            columnExpression15.Table = table3;
            column15.Expression = columnExpression15;
            columnExpression16.ColumnName = "ProductAmount";
            columnExpression16.Table = table3;
            column16.Expression = columnExpression16;
            selectQuery3.Columns.Add(column13);
            selectQuery3.Columns.Add(column14);
            selectQuery3.Columns.Add(column15);
            selectQuery3.Columns.Add(column16);
            selectQuery3.Name = "CustomerReports";
            selectQuery3.Tables.Add(table3);
            columnExpression17.ColumnName = "CustomerID";
            table4.Name = "Customers";
            columnExpression17.Table = table4;
            column17.Expression = columnExpression17;
            columnExpression18.ColumnName = "CompanyName";
            columnExpression18.Table = table4;
            column18.Expression = columnExpression18;
            columnExpression19.ColumnName = "ContactName";
            columnExpression19.Table = table4;
            column19.Expression = columnExpression19;
            columnExpression20.ColumnName = "ContactTitle";
            columnExpression20.Table = table4;
            column20.Expression = columnExpression20;
            columnExpression21.ColumnName = "Address";
            columnExpression21.Table = table4;
            column21.Expression = columnExpression21;
            columnExpression22.ColumnName = "City";
            columnExpression22.Table = table4;
            column22.Expression = columnExpression22;
            columnExpression23.ColumnName = "Region";
            columnExpression23.Table = table4;
            column23.Expression = columnExpression23;
            columnExpression24.ColumnName = "PostalCode";
            columnExpression24.Table = table4;
            column24.Expression = columnExpression24;
            columnExpression25.ColumnName = "Country";
            columnExpression25.Table = table4;
            column25.Expression = columnExpression25;
            columnExpression26.ColumnName = "Phone";
            columnExpression26.Table = table4;
            column26.Expression = columnExpression26;
            columnExpression27.ColumnName = "Fax";
            columnExpression27.Table = table4;
            column27.Expression = columnExpression27;
            selectQuery4.Columns.Add(column17);
            selectQuery4.Columns.Add(column18);
            selectQuery4.Columns.Add(column19);
            selectQuery4.Columns.Add(column20);
            selectQuery4.Columns.Add(column21);
            selectQuery4.Columns.Add(column22);
            selectQuery4.Columns.Add(column23);
            selectQuery4.Columns.Add(column24);
            selectQuery4.Columns.Add(column25);
            selectQuery4.Columns.Add(column26);
            selectQuery4.Columns.Add(column27);
            selectQuery4.Name = "Customers";
            selectQuery4.Tables.Add(table4);
            columnExpression28.ColumnName = "CustomerId";
            table5.Name = "EmployeeCustomers";
            columnExpression28.Table = table5;
            column28.Expression = columnExpression28;
            columnExpression29.ColumnName = "EmployeeId";
            columnExpression29.Table = table5;
            column29.Expression = columnExpression29;
            selectQuery5.Columns.Add(column28);
            selectQuery5.Columns.Add(column29);
            selectQuery5.Name = "EmployeeCustomers";
            selectQuery5.Tables.Add(table5);
            columnExpression30.ColumnName = "EmployeeID";
            table6.Name = "Employees";
            columnExpression30.Table = table6;
            column30.Expression = columnExpression30;
            columnExpression31.ColumnName = "LastName";
            columnExpression31.Table = table6;
            column31.Expression = columnExpression31;
            columnExpression32.ColumnName = "FirstName";
            columnExpression32.Table = table6;
            column32.Expression = columnExpression32;
            columnExpression33.ColumnName = "Title";
            columnExpression33.Table = table6;
            column33.Expression = columnExpression33;
            columnExpression34.ColumnName = "TitleOfCourtesy";
            columnExpression34.Table = table6;
            column34.Expression = columnExpression34;
            columnExpression35.ColumnName = "BirthDate";
            columnExpression35.Table = table6;
            column35.Expression = columnExpression35;
            columnExpression36.ColumnName = "HireDate";
            columnExpression36.Table = table6;
            column36.Expression = columnExpression36;
            columnExpression37.ColumnName = "Address";
            columnExpression37.Table = table6;
            column37.Expression = columnExpression37;
            columnExpression38.ColumnName = "City";
            columnExpression38.Table = table6;
            column38.Expression = columnExpression38;
            columnExpression39.ColumnName = "Region";
            columnExpression39.Table = table6;
            column39.Expression = columnExpression39;
            columnExpression40.ColumnName = "PostalCode";
            columnExpression40.Table = table6;
            column40.Expression = columnExpression40;
            columnExpression41.ColumnName = "Country";
            columnExpression41.Table = table6;
            column41.Expression = columnExpression41;
            columnExpression42.ColumnName = "HomePhone";
            columnExpression42.Table = table6;
            column42.Expression = columnExpression42;
            columnExpression43.ColumnName = "Extension";
            columnExpression43.Table = table6;
            column43.Expression = columnExpression43;
            columnExpression44.ColumnName = "Photo";
            columnExpression44.Table = table6;
            column44.Expression = columnExpression44;
            columnExpression45.ColumnName = "Notes";
            columnExpression45.Table = table6;
            column45.Expression = columnExpression45;
            columnExpression46.ColumnName = "ReportsTo";
            columnExpression46.Table = table6;
            column46.Expression = columnExpression46;
            columnExpression47.ColumnName = "Name";
            columnExpression47.Table = table6;
            column47.Expression = columnExpression47;
            selectQuery6.Columns.Add(column30);
            selectQuery6.Columns.Add(column31);
            selectQuery6.Columns.Add(column32);
            selectQuery6.Columns.Add(column33);
            selectQuery6.Columns.Add(column34);
            selectQuery6.Columns.Add(column35);
            selectQuery6.Columns.Add(column36);
            selectQuery6.Columns.Add(column37);
            selectQuery6.Columns.Add(column38);
            selectQuery6.Columns.Add(column39);
            selectQuery6.Columns.Add(column40);
            selectQuery6.Columns.Add(column41);
            selectQuery6.Columns.Add(column42);
            selectQuery6.Columns.Add(column43);
            selectQuery6.Columns.Add(column44);
            selectQuery6.Columns.Add(column45);
            selectQuery6.Columns.Add(column46);
            selectQuery6.Columns.Add(column47);
            selectQuery6.Name = "Employees";
            selectQuery6.Tables.Add(table6);
            columnExpression48.ColumnName = "ShipName";
            table7.Name = "Invoices";
            columnExpression48.Table = table7;
            column48.Expression = columnExpression48;
            columnExpression49.ColumnName = "ShipAddress";
            columnExpression49.Table = table7;
            column49.Expression = columnExpression49;
            columnExpression50.ColumnName = "ShipCity";
            columnExpression50.Table = table7;
            column50.Expression = columnExpression50;
            columnExpression51.ColumnName = "ShipRegion";
            columnExpression51.Table = table7;
            column51.Expression = columnExpression51;
            columnExpression52.ColumnName = "ShipPostalCode";
            columnExpression52.Table = table7;
            column52.Expression = columnExpression52;
            columnExpression53.ColumnName = "ShipCountry";
            columnExpression53.Table = table7;
            column53.Expression = columnExpression53;
            columnExpression54.ColumnName = "CustomerID";
            columnExpression54.Table = table7;
            column54.Expression = columnExpression54;
            columnExpression55.ColumnName = "Customers.CompanyName";
            columnExpression55.Table = table7;
            column55.Expression = columnExpression55;
            columnExpression56.ColumnName = "Address";
            columnExpression56.Table = table7;
            column56.Expression = columnExpression56;
            columnExpression57.ColumnName = "City";
            columnExpression57.Table = table7;
            column57.Expression = columnExpression57;
            columnExpression58.ColumnName = "Region";
            columnExpression58.Table = table7;
            column58.Expression = columnExpression58;
            columnExpression59.ColumnName = "PostalCode";
            columnExpression59.Table = table7;
            column59.Expression = columnExpression59;
            columnExpression60.ColumnName = "Country";
            columnExpression60.Table = table7;
            column60.Expression = columnExpression60;
            columnExpression61.ColumnName = "Salesperson";
            columnExpression61.Table = table7;
            column61.Expression = columnExpression61;
            columnExpression62.ColumnName = "OrderID";
            columnExpression62.Table = table7;
            column62.Expression = columnExpression62;
            columnExpression63.ColumnName = "OrderDate";
            columnExpression63.Table = table7;
            column63.Expression = columnExpression63;
            columnExpression64.ColumnName = "RequiredDate";
            columnExpression64.Table = table7;
            column64.Expression = columnExpression64;
            columnExpression65.ColumnName = "ShippedDate";
            columnExpression65.Table = table7;
            column65.Expression = columnExpression65;
            columnExpression66.ColumnName = "Shippers.CompanyName";
            columnExpression66.Table = table7;
            column66.Expression = columnExpression66;
            columnExpression67.ColumnName = "ProductID";
            columnExpression67.Table = table7;
            column67.Expression = columnExpression67;
            columnExpression68.ColumnName = "ProductName";
            columnExpression68.Table = table7;
            column68.Expression = columnExpression68;
            columnExpression69.ColumnName = "UnitPrice";
            columnExpression69.Table = table7;
            column69.Expression = columnExpression69;
            columnExpression70.ColumnName = "Quantity";
            columnExpression70.Table = table7;
            column70.Expression = columnExpression70;
            columnExpression71.ColumnName = "Discount";
            columnExpression71.Table = table7;
            column71.Expression = columnExpression71;
            columnExpression72.ColumnName = "ExtendedPrice";
            columnExpression72.Table = table7;
            column72.Expression = columnExpression72;
            columnExpression73.ColumnName = "Freight";
            columnExpression73.Table = table7;
            column73.Expression = columnExpression73;
            selectQuery7.Columns.Add(column48);
            selectQuery7.Columns.Add(column49);
            selectQuery7.Columns.Add(column50);
            selectQuery7.Columns.Add(column51);
            selectQuery7.Columns.Add(column52);
            selectQuery7.Columns.Add(column53);
            selectQuery7.Columns.Add(column54);
            selectQuery7.Columns.Add(column55);
            selectQuery7.Columns.Add(column56);
            selectQuery7.Columns.Add(column57);
            selectQuery7.Columns.Add(column58);
            selectQuery7.Columns.Add(column59);
            selectQuery7.Columns.Add(column60);
            selectQuery7.Columns.Add(column61);
            selectQuery7.Columns.Add(column62);
            selectQuery7.Columns.Add(column63);
            selectQuery7.Columns.Add(column64);
            selectQuery7.Columns.Add(column65);
            selectQuery7.Columns.Add(column66);
            selectQuery7.Columns.Add(column67);
            selectQuery7.Columns.Add(column68);
            selectQuery7.Columns.Add(column69);
            selectQuery7.Columns.Add(column70);
            selectQuery7.Columns.Add(column71);
            selectQuery7.Columns.Add(column72);
            selectQuery7.Columns.Add(column73);
            selectQuery7.Name = "Invoices";
            selectQuery7.Tables.Add(table7);
            columnExpression74.ColumnName = "OrderID";
            table8.Name = "Order Details";
            columnExpression74.Table = table8;
            column74.Expression = columnExpression74;
            columnExpression75.ColumnName = "ProductID";
            columnExpression75.Table = table8;
            column75.Expression = columnExpression75;
            columnExpression76.ColumnName = "UnitPrice";
            columnExpression76.Table = table8;
            column76.Expression = columnExpression76;
            columnExpression77.ColumnName = "Quantity";
            columnExpression77.Table = table8;
            column77.Expression = columnExpression77;
            columnExpression78.ColumnName = "Discount";
            columnExpression78.Table = table8;
            column78.Expression = columnExpression78;
            columnExpression79.ColumnName = "OrderDate";
            columnExpression79.Table = table8;
            column79.Expression = columnExpression79;
            selectQuery8.Columns.Add(column74);
            selectQuery8.Columns.Add(column75);
            selectQuery8.Columns.Add(column76);
            selectQuery8.Columns.Add(column77);
            selectQuery8.Columns.Add(column78);
            selectQuery8.Columns.Add(column79);
            selectQuery8.Name = "Order Details";
            selectQuery8.Tables.Add(table8);
            columnExpression80.ColumnName = "OrderID";
            table9.Name = "OrderReports";
            columnExpression80.Table = table9;
            column80.Expression = columnExpression80;
            columnExpression81.ColumnName = "ProductID";
            columnExpression81.Table = table9;
            column81.Expression = columnExpression81;
            columnExpression82.ColumnName = "ProductName";
            columnExpression82.Table = table9;
            column82.Expression = columnExpression82;
            columnExpression83.ColumnName = "UnitPrice";
            columnExpression83.Table = table9;
            column83.Expression = columnExpression83;
            columnExpression84.ColumnName = "Quantity";
            columnExpression84.Table = table9;
            column84.Expression = columnExpression84;
            columnExpression85.ColumnName = "Discount";
            columnExpression85.Table = table9;
            column85.Expression = columnExpression85;
            columnExpression86.ColumnName = "Extended Price";
            columnExpression86.Table = table9;
            column86.Expression = columnExpression86;
            selectQuery9.Columns.Add(column80);
            selectQuery9.Columns.Add(column81);
            selectQuery9.Columns.Add(column82);
            selectQuery9.Columns.Add(column83);
            selectQuery9.Columns.Add(column84);
            selectQuery9.Columns.Add(column85);
            selectQuery9.Columns.Add(column86);
            selectQuery9.Name = "OrderReports";
            selectQuery9.Tables.Add(table9);
            columnExpression87.ColumnName = "OrderID";
            table10.Name = "Orders";
            columnExpression87.Table = table10;
            column87.Expression = columnExpression87;
            columnExpression88.ColumnName = "CustomerID";
            columnExpression88.Table = table10;
            column88.Expression = columnExpression88;
            columnExpression89.ColumnName = "EmployeeID";
            columnExpression89.Table = table10;
            column89.Expression = columnExpression89;
            columnExpression90.ColumnName = "OrderDate";
            columnExpression90.Table = table10;
            column90.Expression = columnExpression90;
            columnExpression91.ColumnName = "RequiredDate";
            columnExpression91.Table = table10;
            column91.Expression = columnExpression91;
            columnExpression92.ColumnName = "ShippedDate";
            columnExpression92.Table = table10;
            column92.Expression = columnExpression92;
            columnExpression93.ColumnName = "ShipVia";
            columnExpression93.Table = table10;
            column93.Expression = columnExpression93;
            columnExpression94.ColumnName = "Freight";
            columnExpression94.Table = table10;
            column94.Expression = columnExpression94;
            columnExpression95.ColumnName = "ShipName";
            columnExpression95.Table = table10;
            column95.Expression = columnExpression95;
            columnExpression96.ColumnName = "ShipAddress";
            columnExpression96.Table = table10;
            column96.Expression = columnExpression96;
            columnExpression97.ColumnName = "ShipCity";
            columnExpression97.Table = table10;
            column97.Expression = columnExpression97;
            columnExpression98.ColumnName = "ShipRegion";
            columnExpression98.Table = table10;
            column98.Expression = columnExpression98;
            columnExpression99.ColumnName = "ShipPostalCode";
            columnExpression99.Table = table10;
            column99.Expression = columnExpression99;
            columnExpression100.ColumnName = "ShipCountry";
            columnExpression100.Table = table10;
            column100.Expression = columnExpression100;
            selectQuery10.Columns.Add(column87);
            selectQuery10.Columns.Add(column88);
            selectQuery10.Columns.Add(column89);
            selectQuery10.Columns.Add(column90);
            selectQuery10.Columns.Add(column91);
            selectQuery10.Columns.Add(column92);
            selectQuery10.Columns.Add(column93);
            selectQuery10.Columns.Add(column94);
            selectQuery10.Columns.Add(column95);
            selectQuery10.Columns.Add(column96);
            selectQuery10.Columns.Add(column97);
            selectQuery10.Columns.Add(column98);
            selectQuery10.Columns.Add(column99);
            selectQuery10.Columns.Add(column100);
            selectQuery10.Name = "Orders";
            selectQuery10.Tables.Add(table10);
            columnExpression101.ColumnName = "CategoryName";
            table11.Name = "ProductReports";
            columnExpression101.Table = table11;
            column101.Expression = columnExpression101;
            columnExpression102.ColumnName = "ProductName";
            columnExpression102.Table = table11;
            column102.Expression = columnExpression102;
            columnExpression103.ColumnName = "ProductSales";
            columnExpression103.Table = table11;
            column103.Expression = columnExpression103;
            columnExpression104.ColumnName = "ShippedDate";
            columnExpression104.Table = table11;
            column104.Expression = columnExpression104;
            selectQuery11.Columns.Add(column101);
            selectQuery11.Columns.Add(column102);
            selectQuery11.Columns.Add(column103);
            selectQuery11.Columns.Add(column104);
            selectQuery11.Name = "ProductReports";
            selectQuery11.Tables.Add(table11);
            columnExpression105.ColumnName = "ProductID";
            table12.Name = "Products";
            columnExpression105.Table = table12;
            column105.Expression = columnExpression105;
            columnExpression106.ColumnName = "ProductName";
            columnExpression106.Table = table12;
            column106.Expression = columnExpression106;
            columnExpression107.ColumnName = "SupplierID";
            columnExpression107.Table = table12;
            column107.Expression = columnExpression107;
            columnExpression108.ColumnName = "CategoryID";
            columnExpression108.Table = table12;
            column108.Expression = columnExpression108;
            columnExpression109.ColumnName = "QuantityPerUnit";
            columnExpression109.Table = table12;
            column109.Expression = columnExpression109;
            columnExpression110.ColumnName = "UnitPrice";
            columnExpression110.Table = table12;
            column110.Expression = columnExpression110;
            columnExpression111.ColumnName = "UnitsInStock";
            columnExpression111.Table = table12;
            column111.Expression = columnExpression111;
            columnExpression112.ColumnName = "UnitsOnOrder";
            columnExpression112.Table = table12;
            column112.Expression = columnExpression112;
            columnExpression113.ColumnName = "ReorderLevel";
            columnExpression113.Table = table12;
            column113.Expression = columnExpression113;
            columnExpression114.ColumnName = "Discontinued";
            columnExpression114.Table = table12;
            column114.Expression = columnExpression114;
            columnExpression115.ColumnName = "EAN13";
            columnExpression115.Table = table12;
            column115.Expression = columnExpression115;
            selectQuery12.Columns.Add(column105);
            selectQuery12.Columns.Add(column106);
            selectQuery12.Columns.Add(column107);
            selectQuery12.Columns.Add(column108);
            selectQuery12.Columns.Add(column109);
            selectQuery12.Columns.Add(column110);
            selectQuery12.Columns.Add(column111);
            selectQuery12.Columns.Add(column112);
            selectQuery12.Columns.Add(column113);
            selectQuery12.Columns.Add(column114);
            selectQuery12.Columns.Add(column115);
            selectQuery12.Name = "Products";
            selectQuery12.Tables.Add(table12);
            columnExpression116.ColumnName = "EmployeeID";
            table13.Name = "SalesByCategory";
            columnExpression116.Table = table13;
            column116.Expression = columnExpression116;
            columnExpression117.ColumnName = "CategoryName";
            columnExpression117.Table = table13;
            column117.Expression = columnExpression117;
            columnExpression118.ColumnName = "SumOfQuantity";
            columnExpression118.Table = table13;
            column118.Expression = columnExpression118;
            selectQuery13.Columns.Add(column116);
            selectQuery13.Columns.Add(column117);
            selectQuery13.Columns.Add(column118);
            selectQuery13.Name = "SalesByCategory";
            selectQuery13.Tables.Add(table13);
            columnExpression119.ColumnName = "OrderID";
            table14.Name = "SalesPerson";
            columnExpression119.Table = table14;
            column119.Expression = columnExpression119;
            columnExpression120.ColumnName = "Country";
            columnExpression120.Table = table14;
            column120.Expression = columnExpression120;
            columnExpression121.ColumnName = "FirstName";
            columnExpression121.Table = table14;
            column121.Expression = columnExpression121;
            columnExpression122.ColumnName = "LastName";
            columnExpression122.Table = table14;
            column122.Expression = columnExpression122;
            columnExpression123.ColumnName = "ProductName";
            columnExpression123.Table = table14;
            column123.Expression = columnExpression123;
            columnExpression124.ColumnName = "CategoryName";
            columnExpression124.Table = table14;
            column124.Expression = columnExpression124;
            columnExpression125.ColumnName = "OrderDate";
            columnExpression125.Table = table14;
            column125.Expression = columnExpression125;
            columnExpression126.ColumnName = "UnitPrice";
            columnExpression126.Table = table14;
            column126.Expression = columnExpression126;
            columnExpression127.ColumnName = "Quantity";
            columnExpression127.Table = table14;
            column127.Expression = columnExpression127;
            columnExpression128.ColumnName = "Discount";
            columnExpression128.Table = table14;
            column128.Expression = columnExpression128;
            columnExpression129.ColumnName = "Extended Price";
            columnExpression129.Table = table14;
            column129.Expression = columnExpression129;
            columnExpression130.ColumnName = "Sales Person";
            columnExpression130.Table = table14;
            column130.Expression = columnExpression130;
            selectQuery14.Columns.Add(column119);
            selectQuery14.Columns.Add(column120);
            selectQuery14.Columns.Add(column121);
            selectQuery14.Columns.Add(column122);
            selectQuery14.Columns.Add(column123);
            selectQuery14.Columns.Add(column124);
            selectQuery14.Columns.Add(column125);
            selectQuery14.Columns.Add(column126);
            selectQuery14.Columns.Add(column127);
            selectQuery14.Columns.Add(column128);
            selectQuery14.Columns.Add(column129);
            selectQuery14.Columns.Add(column130);
            selectQuery14.Name = "SalesPerson";
            selectQuery14.Tables.Add(table14);
            columnExpression131.ColumnName = "ShipperID";
            table15.Name = "Shippers";
            columnExpression131.Table = table15;
            column131.Expression = columnExpression131;
            columnExpression132.ColumnName = "CompanyName";
            columnExpression132.Table = table15;
            column132.Expression = columnExpression132;
            columnExpression133.ColumnName = "Phone";
            columnExpression133.Table = table15;
            column133.Expression = columnExpression133;
            selectQuery15.Columns.Add(column131);
            selectQuery15.Columns.Add(column132);
            selectQuery15.Columns.Add(column133);
            selectQuery15.Name = "Shippers";
            selectQuery15.Tables.Add(table15);
            columnExpression134.ColumnName = "SupplierID";
            table16.Name = "Suppliers";
            columnExpression134.Table = table16;
            column134.Expression = columnExpression134;
            columnExpression135.ColumnName = "CompanyName";
            columnExpression135.Table = table16;
            column135.Expression = columnExpression135;
            columnExpression136.ColumnName = "ContactName";
            columnExpression136.Table = table16;
            column136.Expression = columnExpression136;
            columnExpression137.ColumnName = "ContactTitle";
            columnExpression137.Table = table16;
            column137.Expression = columnExpression137;
            columnExpression138.ColumnName = "Address";
            columnExpression138.Table = table16;
            column138.Expression = columnExpression138;
            columnExpression139.ColumnName = "City";
            columnExpression139.Table = table16;
            column139.Expression = columnExpression139;
            columnExpression140.ColumnName = "Region";
            columnExpression140.Table = table16;
            column140.Expression = columnExpression140;
            columnExpression141.ColumnName = "PostalCode";
            columnExpression141.Table = table16;
            column141.Expression = columnExpression141;
            columnExpression142.ColumnName = "Country";
            columnExpression142.Table = table16;
            column142.Expression = columnExpression142;
            columnExpression143.ColumnName = "Phone";
            columnExpression143.Table = table16;
            column143.Expression = columnExpression143;
            columnExpression144.ColumnName = "Fax";
            columnExpression144.Table = table16;
            column144.Expression = columnExpression144;
            columnExpression145.ColumnName = "HomePage";
            columnExpression145.Table = table16;
            column145.Expression = columnExpression145;
            selectQuery16.Columns.Add(column134);
            selectQuery16.Columns.Add(column135);
            selectQuery16.Columns.Add(column136);
            selectQuery16.Columns.Add(column137);
            selectQuery16.Columns.Add(column138);
            selectQuery16.Columns.Add(column139);
            selectQuery16.Columns.Add(column140);
            selectQuery16.Columns.Add(column141);
            selectQuery16.Columns.Add(column142);
            selectQuery16.Columns.Add(column143);
            selectQuery16.Columns.Add(column144);
            selectQuery16.Columns.Add(column145);
            selectQuery16.Name = "Suppliers";
            selectQuery16.Tables.Add(table16);
            this.sqlDataSource1.Queries.AddRange(new DevExpress.DataAccess.Sql.SqlQuery[] {
            selectQuery1,
            selectQuery2,
            selectQuery3,
            selectQuery4,
            selectQuery5,
            selectQuery6,
            selectQuery7,
            selectQuery8,
            selectQuery9,
            selectQuery10,
            selectQuery11,
            selectQuery12,
            selectQuery13,
            selectQuery14,
            selectQuery15,
            selectQuery16});
            this.sqlDataSource1.ResultSchemaSerializable = resources.GetString("sqlDataSource1.ResultSchemaSerializable");
            // 
            // AllTables
            // 
            this.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.TopMargin,
            this.BottomMargin,
            this.Detail});
            this.ComponentStorage.AddRange(new System.ComponentModel.IComponent[] {
            this.sqlDataSource1});
            this.DataSource = this.sqlDataSource1;
            this.Font = new DevExpress.Drawing.DXFont("Arial", 9.75F);
            this.Version = "23.2";
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();

        }

        #endregion

        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
    }
}
